plugins {
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
    id "kotlin-kapt"
    id "dagger.hilt.android.plugin"
    id "androidx.navigation.safeargs.kotlin"
}

def gitCommitHash = "git rev-parse --verify --short HEAD".execute().text.trim()
def keyProps = new Properties()
def keyPropsFile = rootProject.file("signature/keystore.properties")
if (keyPropsFile.exists()) {
    println("Loading keystore properties from ${keyPropsFile.absolutePath}")
    keyProps.load(new FileInputStream(keyPropsFile))
}

android {
    namespace 'com.mckimquyen.reader'
    compileSdk 36
    defaultConfig {
        applicationId "com.mckimquyen.reader"
        minSdk 26
        //noinspection EditedTargetSdkVersion,OldTargetApi
        targetSdk 36
        versionCode 20250929
        versionName "2025.09.29"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }

        // Keep only major languages to reduce APK size
        resourceConfigurations += ['en', 'vi', 'zh-rCN', 'ja', 'fr', 'de']

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += [
                        "room.schemaLocation": "$projectDir/schemas".toString(),
                        "room.incremental"   : "true"
                ]
            }
        }
    }

//    lint {
//        baseline = file("lint-baseline.xml")
//    }

    flavorDimensions.add("channel")
    productFlavors {
        dev {
            dimension "channel"
        }
        prod {
            dimension "channel"
        }
    }
    signingConfigs {
        release {
            storeFile file("keystores.jks")
            storePassword "27072000"
            keyAlias "mckimquyen"
            keyPassword "27072000"
        }
    }
    buildTypes {
        debug {
            buildConfigField "String", "ADMOB_BANNER_ID", "\"ca-app-pub-3940256099942544/6300978111\""
            buildConfigField "String", "ADMOB_INTERSTITIAL_ID", "\"ca-app-pub-3940256099942544/1033173712\""
            buildConfigField "String", "ADMOB_APP_OPEN_ID", "\"ca-app-pub-3940256099942544/9257395921\""
        }

        release {
            // nhớ check APPLICATION_ID trong manifest
            buildConfigField "String", "ADMOB_BANNER_ID", "\"ca-app-pub-3612191981543807/6401478547\""
            buildConfigField "String", "ADMOB_INTERSTITIAL_ID", "\"ca-app-pub-3612191981543807/4529159528\""
            buildConfigField "String", "ADMOB_APP_OPEN_ID", "\"ca-app-pub-3612191981543807/4028490288\""

            signingConfig signingConfigs.release
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    applicationVariants.configureEach { variant ->
        variant.outputs.each { output ->
            output.outputFileName = "RSS Cat Hub-${defaultConfig.versionName}-${gitCommitHash}.apk"
        }
    }
    kotlinOptions {
        freeCompilerArgs = freeCompilerArgs + "-opt-in=kotlin.RequiresOptIn"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        compose true
//        viewBinding true
        buildConfig true
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.2.0-beta02'
    }
    packagingOptions {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
            excludes += "/META-INF/*.kotlin_module"
            excludes += "/META-INF/DEPENDENCIES"
            excludes += "/META-INF/LICENSE*"
            excludes += "/META-INF/NOTICE*"
            excludes += "/META-INF/*.properties"
            excludes += "/META-INF/*.version"
            excludes += "/*.properties"
            excludes += "DebugProbesKt.bin"
        }
        jniLibs {
            useLegacyPackaging = false
        }
    }
}

dependencies {
//    api "androidx.compose.compiler:compiler:1.5.15"
    api "com.github.ireward:compose-html:1.0.2"
    api "com.caverock:androidsvg-aar:$androidSVG"
    api "be.ceau:opml-parser:$opmlParser"
    api "net.dankito.readability4j:readability4j:$readability4j"
    api "com.rometools:rome:2.1.0"
    api("io.coil-kt:coil-base:2.1.0")
    api("io.coil-kt:coil-compose:2.1.0")
    api("io.coil-kt:coil-svg:2.1.0")
    api("io.coil-kt:coil-gif:2.1.0")

//    api "com.squareup.okhttp3:okhttp:5.0.0-alpha.11"
    api "com.squareup.okhttp3:okhttp-coroutines-jvm:5.0.0-alpha.11"
    api "com.squareup.retrofit2:retrofit:2.9.0"
    api "com.squareup.retrofit2:converter-gson:2.9.0"
    api "androidx.profileinstaller:profileinstaller:1.4.1"
    api "androidx.work:work-runtime-ktx:2.8.0-alpha02"
    api "androidx.datastore:datastore-preferences:1.0.0"

    api "androidx.room:room-paging:2.5.2"
    api "androidx.room:room-common:2.5.2"
    api "androidx.room:room-ktx:2.5.2"
    //noinspection KaptUsageInsteadOfKsp
    kapt "androidx.room:room-compiler:2.5.2"

//    api "androidx.paging:paging-common:3.1.1"
//    api "androidx.paging:paging-runtime:3.1.1"
    api "androidx.paging:paging-compose:1.0.0-alpha14"
    api "androidx.browser:browser:1.8.0"

    api "androidx.navigation:navigation-compose:2.5.0-rc01"
//    api "androidx.lifecycle:lifecycle-viewmodel-compose:2.5.0-rc01"
//    api "androidx.lifecycle:lifecycle-runtime-ktx:2.5.0-rc01"

    api "androidx.compose.material3:material3:1.0.1"
//    api "com.google.accompanist:accompanist-insets:0.24.7-alpha"
    api "com.google.accompanist:accompanist-systemuicontroller:0.24.7-alpha"
    api "com.google.accompanist:accompanist-pager:0.24.7-alpha"
    api "com.google.accompanist:accompanist-flowlayout:0.24.7-alpha"
    api "com.google.accompanist:accompanist-navigation-animation:0.24.7-alpha"
    api "com.google.accompanist:accompanist-swiperefresh:0.24.7-alpha"

//    api "androidx.compose.animation:animation-graphics:1.2.0-beta02"
//    api "androidx.compose.ui:ui:1.2.0-beta02"
    api "androidx.compose.ui:ui-util:1.2.0-beta02"
    api "androidx.compose.material:material:1.2.0-beta02"
    api "androidx.compose.material:material-icons-extended:1.2.0-beta02"
    api "androidx.compose.ui:ui-tooling-preview:1.2.0-beta02"

    api "androidx.hilt:hilt-work:1.0.0"
    api "com.google.dagger:hilt-android:2.40.5"
    kapt "com.google.dagger:hilt-android-compiler:2.40.5"
    api "androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha03"
    kapt "androidx.hilt:hilt-compiler:1.0.0"
    api "androidx.hilt:hilt-navigation-compose:1.0.0"
    api "androidx.core:core-ktx:1.7.0"
    api "androidx.activity:activity-compose:1.4.0"
    implementation("com.google.android.play:review:2.0.1")
    implementation("com.google.android.play:review-ktx:2.0.1")

    implementation("com.google.android.gms:play-services-ads:22.3.0")
    implementation("com.google.ads.mediation:applovin:11.11.3.0")
//    implementation("androidx.appcompat:appcompat:1.7.0")

    testImplementation "junit:junit:4.13.2"
    testImplementation "io.mockk:mockk:1.13.5"
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.4"
    androidTestImplementation "androidx.test.ext:junit:1.1.5"
    androidTestImplementation "androidx.test.espresso:espresso-core:3.5.1"
    debugImplementation("com.squareup.leakcanary:leakcanary-android:2.14")
}
