package com.mckimquyen.reader.domain.model.article

import androidx.annotation.Keep
import java.util.UUID

/**
 * Sender type for an AI Deep Read conversational turn.
 */
enum class DeepReadSender {
    USER,
    ASSISTANT
}

/**
 * An individual message turn within an article chat session.
 *
 * @param id Unique identifier for this message.
 * @param sender [DeepReadSender.USER] or [DeepReadSender.ASSISTANT].
 * @param content Text body of the message.
 * @param timestamp Epoch timestamp in milliseconds.
 * @param isOfflineFallback True if answer was generated by local heuristic extraction rather than cloud AI.
 * @param isGrounded True if answer was directly supported by article facts.
 */
@Keep
data class DeepReadMessage(
    val id: String = UUID.randomUUID().toString(),
    val sender: DeepReadSender,
    val content: String,
    val timestamp: Long = System.currentTimeMillis(),
    val isOfflineFallback: Boolean = false,
    val isGrounded: Boolean = true,
)

/**
 * Session representing a complete interactive Q&A dialogue about a specific article.
 *
 * @param articleId ID of the article being discussed.
 * @param articleTitle Headline of the article.
 * @param messages Ordered list of turns in the conversation.
 * @param suggestedChips Quick prompt chips dynamically derived from the article content.
 */
@Keep
data class DeepReadSession(
    val articleId: String = "",
    val articleTitle: String = "",
    val messages: List<DeepReadMessage> = emptyList(),
    val suggestedChips: List<String> = emptyList(),
) {
    /**
     * Formats the conversation history into a clean shareable transcript.
     */
    fun formatTranscript(): String = buildString {
        appendLine("💬 AI Deep Read: ${articleTitle.ifBlank { "Article Discussion" }}")
        appendLine()
        messages.forEach { msg ->
            val prefix = if (msg.sender == DeepReadSender.USER) "👤 You" else "✨ AI Assistant"
            val fallbackTag = if (msg.isOfflineFallback) " [Offline Smart]" else ""
            appendLine("$prefix$fallbackTag:")
            appendLine(msg.content.trim())
            appendLine()
        }
    }.trim()
}
